#!/system/bin/sh

set -xe

## INSTRUCTIONS
#
#  1. Download and open the Android port of Emacs
#  2. Give it storage permissions
#  3. Open M-x term or M-x ansi-term and go to where you downloaded this file (probably /storage/emulated/0/Download/emacs-android-setup)
#  4. Copy it to ~/emacs-android-setup
#  5. Make it executable
#  6. Run it

if [ "$(pwd)" = "$HOME" ]; then
    echo "Ok"
else
    echo "Not ok. This file must be at ~."
    exit 1
fi

rm -rf ~/.emacs
cd ~
mkdir -p tmp
cd tmp
curl -fsSL https://codeberg.org/benja2998/dotfiles/archive/main.zip -o main.zip
unzip main.zip
mv ~/tmp/dotfiles/configs/.emacs ~/.emacs
mkdir -p ~/.emacs.d/eshell/
rm -r ~/.emacs.d/local/
mv ~/tmp/dotfiles/configs/.emacs.d/local/ ~/.emacs.d/local/
mv ~/tmp/dotfiles/configs/.emacs.d/eshell/alias ~/.emacs.d/eshell/alias 
cd ~
rm -rf tmp
