#!/bin/bash

set -ex

if [[ -f /etc/os-release ]]; then
    . /etc/os-release
    if [[ "$NAME" = "Void" ]]; then
	sudo xbps-install gnupg git base-devel emacs-x11
    fi
elif [[ -v "$PREFIX" ]]; then
    pkg i -y termux-services gnupg git build-essential emacs-x
fi

mkdir -p ~/.gnupg
mkdir -p ~/.config

# gsettings set org.gnome.desktop.default-applications.terminal exec 'st'

dotfiles="$(pwd)"

# dconf load /org/gnome/desktop/ < desktop.dconf
# dconf load /org/gnome/shell/ < shell.dconf

stow -v --target ~ configs
mkdir -p ~/.config/gtk-4.0
cp "$dotfiles/manualcopy/gtk-4.0/gtk.css" ~/.config/gtk-4.0/gtk.css
