#!/bin/sh

printf "Have you set up GPG keys and set up git to always sign with GPG? (answer yes or no): "

read -r answer

if [ "$answer" = "yes" ]; then
    printf "Continuing\n"
elif [ "$answer" = "no" ]; then
    printf "Not continuing!!\n"
    exit 1
else
    printf "Bad answer!!\n"
    exit 1
fi

mkdir -p ~/.config
mkdir -p ~/.emacs.d
mkdir -p ~/.gnupg

printf "Checking if HOME is parent of current dir...\n"

dotfiles=$(pwd)

cd ..
parent=$(pwd)

cd "$dotfiles"

if [ "$parent" = "$HOME" ]; then
    printf "Parent is HOME, continuing\n"
else
    printf "Parent is not HOME!!\n"
    exit 1
fi

printf "Installing programs...\n"

pkg_cmd="sudo apt-get install -y" # Default

if [ -n "$TERMUX_VERSION" ]; then
    pkg_cmd="pkg i -y"
    pkgs="emacs termux-services build-essential stow ripgrep fzf"
elif [ "$(uname)" = "Darwin" ]; then
    pkg_cmd="brew install"
    pkgs="gcc make fzf ripgrep stow"
    casks="emacs-app firefox"
elif [ "$(uname)" = "Linux" ]; then
    . /etc/os-release
    if [ "$ID_LIKE" = "debian" ] || [ "$ID" = "debian" ]; then
	    pkg_cmd="sudo apt-get install -y"
	    pkgs="build-essential emacs fzf stow ripgrep"
    else
	    printf "Unsupported distro!!\n"
	    exit 1
    fi
else
    printf "Unsupported OS!!\n"
    exit 1
fi

if [ "$(uname)" = "Darwin" ]; then
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    eval "$(/opt/homebrew/bin/brew shellenv)"
fi

# Perform the installation
printf "Running: $pkg_cmd $pkgs\n"
$pkg_cmd $pkgs

if [ "$(uname)" = "Darwin" ]; then
    $pkg_cmd --cask $casks
fi

if [ -x "$(command -v stow)" ]; then
    printf "Continuing to main logic\n"
else
    printf "Stow is not installed!!\n"
    exit 1
fi

printf "Do you want to install every package, or only some? (answer every or some): "

read -r answer
n
if [ "$answer" = "every" ]; then
    rm ~/.emacs.d/init.el -v
    rm ~/.emacs.d/custom.el -v
    rm ~/.bashrc -v
    rm ~/.nanorc -v
    rm ~/.zshrc -v
    rm ~/.emacs.d/local -rv
    rm ~/.config/fastfetch -rv
    rm ~/.gnupg/gpg-agent.conf -v
    rm ~/.gnupg/gpg.conf -v
    stow */ -v
elif [ "$answer" = "some" ]; then
    printf "Package to install?: "
    read -r package
    if [ "$package" = "" ]; then
	    printf "No package!!\n"
	    exit 1
    fi
    stow "$package" -v
else
    printf "Bad answer!!\n"
    exit 1
fi

set -e

printf "Git email: "
read -r email
printf "Git username: "
read -r name
git config --global user.email "$email"
git config --global user.name "$name"
git config --global core.editor nano
git config --global init.defaultBranch main

set +e
emacs --batch --eval "(package-install 'magit)"
emacs --batch --eval "(package-install 'eat)"
killall emacs
