(deftheme arcdark
  "Theme based on the Arc GTK Theme")

(custom-theme-set-faces
 'arcdark
 '(cursor ((t (:background "#ffffff"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((t (:foreground "#ff5f59"))))
 '(homoglyph ((t (:foreground "#fec43f"))))
 '(minibuffer-prompt ((t (:inherit (modus-themes-prompt)))))
 '(highlight ((t (:background "#45605e" :foreground "#ffffff"))))
 '(region ((t (:extend t :background "#5294e2" :foreground "#ffffff"))))
 '(shadow ((t (:foreground "#989898"))))
 '(secondary-selection ((t (:extend t :foreground "#ffffff" :background "#654a39"))))
 '(trailing-whitespace ((t (:background "#9d1f1f"))))
 '(font-lock-bracket-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-builtin-face ((t (:foreground "#f78fe7" :inherit (modus-themes-bold)))))
 '(font-lock-comment-delimiter-face ((t (:inherit font-lock-comment-face))))
 '(font-lock-comment-face ((t (:inherit modus-themes-slant :foreground "#A8A8A8"))))
 '(font-lock-constant-face ((t (:foreground "#00bcff"))))
 '(font-lock-delimiter-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-doc-face ((t (:foreground "#9ac8e0" :inherit (modus-themes-slant)))))
 '(font-lock-doc-markup-face ((t (:foreground "#caa6df" :inherit (modus-themes-slant)))))
 '(font-lock-escape-face ((t (:inherit (font-lock-regexp-grouping-backslash)))))
 '(font-lock-function-call-face ((t (:inherit (font-lock-function-name-face)))))
 '(font-lock-function-name-face ((t (:foreground "#feacd0"))))
 '(font-lock-keyword-face ((t (:foreground "#b6a0ff" :inherit (modus-themes-bold)))))
 '(font-lock-negation-char-face ((t (:inherit (error)))))
 '(font-lock-number-face ((t nil)))
 '(font-lock-misc-punctuation-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-operator-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:foreground "#ff7f9f"))))
 '(font-lock-property-name-face ((t (:inherit (font-lock-variable-name-face)))))
 '(font-lock-property-use-face ((t (:inherit (font-lock-property-name-face)))))
 '(font-lock-punctuation-face ((t nil)))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#feacd0" :inherit (modus-themes-bold)))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#00c06f" :inherit (modus-themes-bold)))))
 '(font-lock-string-face ((t (:foreground "#79a8ff"))))
 '(font-lock-type-face ((t (:foreground "#6ae4b9" :inherit (modus-themes-bold)))))
 '(font-lock-variable-name-face ((t (:foreground "#00d3d0"))))
 '(font-lock-variable-use-face ((t (:inherit (font-lock-variable-name-face)))))
 '(font-lock-warning-face ((t (:foreground "#fec43f" :inherit (modus-themes-bold)))))
 '(button ((t (:foreground "#79a8ff" :underline "#79a8ff"))))
 '(link ((t (:inherit (button)))))
 '(link-visited ((t (:foreground "#feacd0" :underline "#feacd0"))))
 '(fringe ((t (:inherit default))))
 '(header-line ((t (:background "#1e1e1e" :inherit modus-themes-ui-variable-pitch))))
 '(tooltip ((t (:background "#383C4A" :foreground "#D3DAE3"))))
 '(mode-line ((t (:box (:line-width (1 . 1) :color "#404552") :foreground "#D3DAE3" :background "#383C4A" :inherit modus-themes-ui-variable-pitch))))
 '(mode-line-buffer-id ((t (:inherit (bold)))))
 '(mode-line-emphasis ((t (:inherit bold :foreground "#9fefff"))))
 '(mode-line-highlight ((t (:box (:line-width (1 . 1) :color "#ffffff" :style nil) :foreground "#ffffff" :background "#45605e"))))
 '(mode-line-inactive ((t (:inherit modus-themes-ui-variable-pitch :background "#323843" :foreground "#D3DAE3" :box (:line-width (1 . 1) :color "#323843")))))
 '(isearch ((t (:inherit (modus-themes-search-current)))))
 '(isearch-fail ((t (:inherit (modus-themes-prominent-error)))))
 '(lazy-highlight ((t (:inherit (modus-themes-search-lazy)))))
 '(match ((t (:foreground "#ffffff" :background "#552f5f"))))
 '(next-error ((t (:extend t :inherit (modus-themes-prominent-error)))))
 '(query-replace ((t (:inherit (modus-themes-search-replace)))))
 '(magit-diff-hunk-heading ((t (:inherit default :extend t))))
 '(magit-diff-file-heading-highlight ((t (:inherit (magit-section-highlight default) :extend t :background "#404552"))))
 '(default ((t (:inherit nil :extend nil :stipple nil :background "#2f343f" :foreground "#D3DAE3" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight regular :height 158 :width normal :foundry "PfEd" :family "DejaVu Sans Mono"))))
 '(magit-blame-highlight ((t (:extend t :background "#404552" :foreground "white"))))
 '(magit-section-highlight ((t (:extend t :background "#404552")))))

(provide-theme 'arcdark)
