#+PROPERTY: header-args :results silent

* Emacs Config

** Options

The custom file should not exist. The closest thing to making it never be created is this.

#+BEGIN_SRC elisp
  (setq custom-file (make-temp-file "emacs-custom"))
#+END_SRC

On macOS, both option keys are meta. On my keyboard layout, you need right option to type special characters, so I fix this like this.

#+BEGIN_SRC elisp
  (setq mac-option-modifier 'meta)
  (setq mac-right-option-modifier 'none)
#+END_SRC

Typing 'yes' every time is annoying. Luckily, the fix is easy.

#+BEGIN_SRC elisp
  (setq use-short-answers t)
#+END_SRC

Relative line numbers allow faster navigation, so i am enabling them.

#+BEGIN_SRC elisp
  (setq display-line-numbers-type 'relative)
#+END_SRC

I want a clean UI.

#+BEGIN_SRC elisp
  (menu-bar-mode 0)
  (scroll-bar-mode 0)
  (tool-bar-mode 0)
#+END_SRC

Now I need to make emacs less annoying.

#+BEGIN_SRC elisp
  (setq inhibit-splash-screen t)
  (setq make-backup-files nil)
  (setq auto-save-default nil)
  (setq create-lockfiles nil)
  (setq tramp-auto-save-directory "/tmp")
#+END_SRC

** Packages

I need to set up the package manager.

#+BEGIN_SRC elisp
  (require 'package)

  (setq package-archives
        '(("gnu"   . "https://elpa.gnu.org/packages/")
          ("melpa" . "https://melpa.org/packages/")
          ("nongnu" . "https://elpa.nongnu.org/nongnu/")))

  (package-initialize)

  (require 'use-package)
  (setq use-package-always-ensure t)
#+END_SRC

Now install the packages.

#+BEGIN_SRC elisp
  (use-package vertico
    :custom
    (vertico-scroll-margin 0) ;; Different scroll margin
    (vertico-count 20) ;; Show more candidates
    (vertico-resize t) ;; Grow and shrink the Vertico minibuffer
    (vertico-cycle t) ;; Enable cycling for `vertico-next/previous'
    :init
    (vertico-mode))

  ;; Persist history over Emacs restarts. Vertico sorts by history position.
  (use-package savehist
    :init
    (savehist-mode))

  ;; Emacs minibuffer configurations.
  (use-package emacs
    :custom
    ;; Enable context menu. `vertico-multiform-mode' adds a menu in the minibuffer
    ;; to switch display modes.
    (context-menu-mode t)
    ;; Support opening new minibuffers from inside existing minibuffers.
    (enable-recursive-minibuffers t)
    ;; Hide commands in M-x which do not work in the current mode.  Vertico
    ;; commands are hidden in normal buffers. This setting is useful beyond
    ;; Vertico.
    (read-extended-command-predicate #'command-completion-default-include-p)
    ;; Do not allow the cursor in the minibuffer prompt
    (minibuffer-prompt-properties
     '(read-only t cursor-intangible t face minibuffer-prompt)))

  (use-package orderless
    :ensure t
    :custom
    (orderless-matching-styles '(orderless-literal orderless-regexp orderless-flex))
    (completion-styles '(orderless basic))
    (completion-category-overrides '((file (styles partial-completion))))
    (completion-pcm-leading-wildcard t)) ;; Emacs 31: partial-completion behaves like substring

  (use-package magit
    :bind ("C-c g" . magit-status))

  (use-package markdown-mode
    :mode (("\\.md\\'" . markdown-mode)
           ("\\.markdown\\'" . markdown-mode))
    :init
    (setq markdown-command "pandoc"))

  (use-package typescript-mode
    :mode "\\.ts\\'")

  (use-package lua-mode
    :mode "\\.lua\\'")

  (use-package fish-mode
    :mode "\\.fish\\'")

  (use-package rust-mode
    :mode "\\.rs\\'")

  (use-package org-superstar
    :hook (org-mode . org-superstar-mode))

  (use-package doom-modeline
    :ensure t
    :init (doom-modeline-mode 1))

  (use-package nerd-icons)

  (use-package catppuccin-theme)

  (use-package god-mode)

  (use-package key-chord)
#+END_SRC

** God Mode

Modal editing to avoid pinky strain.

#+BEGIN_SRC elisp
  (require 'god-mode)
  (god-mode-all)
#+END_SRC

** Key Chord

Allow mapping simultaneous presses of keys.

#+BEGIN_SRC elisp
  (require 'key-chord)
  (key-chord-mode 1)
#+END_SRC

** Colors

I use the Catppuccin theme.

#+BEGIN_SRC elisp
  (setq catppuccin-flavor 'mocha)
  (load-theme 'catppuccin :no-confirm)
#+END_SRC

** Keys

Keys for faster and more precise window navigation with Windmove.

#+BEGIN_SRC elisp
  (global-set-key (kbd "M-j") #'windmove-left)
  (global-set-key (kbd "M-l") #'windmove-right)
  (global-set-key (kbd "M-i") #'windmove-up)
  (global-set-key (kbd "M-k") #'windmove-down)
#+END_SRC

I want to open Eat quickly.

#+BEGIN_SRC elisp
  (global-set-key (kbd "C-c t") 'eat)
#+END_SRC

Unset some keys I often accidentally hit.

#+BEGIN_SRC elisp
  (global-unset-key (kbd "C-x C-b"))
  (global-unset-key (kbd "C-x C-d"))
#+END_SRC

I want C-x ps to open Eat instead.

#+BEGIN_SRC elisp
  (with-eval-after-load 'project
    (define-key project-prefix-map (kbd "s") #'eat-project))
#+END_SRC

I want to toggle God Mode using a key.

#+BEGIN_SRC elisp
  (key-chord-define-global "jk" 'god-local-mode)
#+END_SRC

** Font

I need to be able to read my code.

#+BEGIN_SRC elisp
  (set-face-attribute 'default nil :font "JetBrainsMono Nerd Font" :height 140)
#+END_SRC

** LSP

I want my editor to be smart.

I need to require Eglot, which is the client built into emacs and is extremely easy to set up.

#+BEGIN_SRC elisp
  (require 'eglot)
#+END_SRC

Now I need to configure each LSP I need.

#+BEGIN_SRC elisp
  (add-hook 'typescript-mode-hook #'eglot-ensure)
  (add-hook 'js-mode-hook #'eglot-ensure)
  (add-hook 'c-mode-hook #'eglot-ensure)
  (add-hook 'c++-mode-hook #'eglot-ensure)
  (add-hook 'rust-mode-hook #'eglot-ensure)
#+END_SRC

** Word wrap

Most people disable word wrap in other editors. But I am enabling it.

#+BEGIN_SRC elisp
  (global-visual-line-mode t)
#+END_SRC

** Hooks

I set emacsclient as my default Git editor. I wanted to get Magit commit UI in the buffer, and the method I found was to load it on start like this.

#+BEGIN_SRC elisp
  (add-hook 'emacs-startup-hook 'magit-status)
  (add-hook 'emacs-startup-hook 'magit-mode-bury-buffer t)
#+END_SRC

I want to only display line numbers when it makes sense to.

#+BEGIN_SRC elisp
  (add-hook 'prog-mode-hook 'display-line-numbers-mode)
  (add-hook 'text-mode-hook 'display-line-numbers-mode)
  (add-hook 'conf-mode-hook 'display-line-numbers-mode)
#+END_SRC

I want eshell to be captured by eat.

#+BEGIN_SRC elisp
  (add-hook 'eshell-load-hook #'eat-eshell-mode)
#+END_SRC
